import type {
  Artifact,
  AuditEvent,
  DistributionEndpoint,
  LogCenterEvent,
  Product,
  ReleaseRecord,
  ScmConnection,
} from './types';

export const products: Product[] = [
  {
    id: 'ngep',
    name: 'Next-Gen Enterprise Portal',
    description: '企业门户桌面端与服务端可信发布',
    defaultChannel: 'stable',
    channels: ['stable', 'preview'],
    status: 'active',
    manifestDigest: 'sha256:8b9c…7a12',
    updatedAt: '2026-08-20 13:42',
  },
  {
    id: 'xminds-agent',
    name: 'Xminds Agent',
    description: '终端更新代理与诊断工具',
    defaultChannel: 'stable',
    channels: ['stable', 'beta'],
    status: 'active',
    manifestDigest: 'sha256:2f19…c083',
    updatedAt: '2026-08-20 11:18',
  },
];

export const artifacts: Artifact[] = [
  {
    id: 'artifact-1',
    product: 'ngep',
    filename: 'ngep-desktop-1.2.3-arm64.dmg',
    version: '1.2.3',
    size: '186.4 MiB',
    sha256: '8fb91b52074c7da7d9a7…27ce5d98',
    status: 'verified',
    progress: 100,
    updatedAt: '2026-08-20 13:31',
  },
  {
    id: 'artifact-2',
    product: 'xminds-agent',
    filename: 'xminds-agent-0.9.8-linux-amd64.tar.gz',
    version: '0.9.8',
    size: '42.7 MiB',
    sha256: '119e2b78fe17e844f03e…9b4f5d30',
    status: 'verified',
    progress: 100,
    updatedAt: '2026-08-20 11:07',
  },
];

export const releases: ReleaseRecord[] = [
  {
    id: 'release-1',
    product: 'ngep',
    version: '1.2.3',
    channel: 'stable',
    status: 'submitted',
    submittedBy: 'alice',
    updatedAt: '2026-08-20 13:46',
    notes: '修复企业 CA 更新与登录审计请求链路，升级桌面端更新代理。',
    artifacts: ['ngep-desktop-1.2.3-arm64.dmg'],
  },
  {
    id: 'release-2',
    product: 'ngep',
    version: '1.2.2',
    channel: 'stable',
    status: 'published',
    submittedBy: 'carol',
    updatedAt: '2026-08-19 18:20',
    notes: '稳定性更新。',
    artifacts: ['ngep-desktop-1.2.2-arm64.dmg'],
  },
  {
    id: 'release-3',
    product: 'xminds-agent',
    version: '0.9.8',
    channel: 'beta',
    status: 'failed',
    submittedBy: 'alice',
    updatedAt: '2026-08-20 11:26',
    notes: '新增端点摘要回读校验。',
    artifacts: ['xminds-agent-0.9.8-linux-amd64.tar.gz'],
  },
];

export const scmConnections: ScmConnection[] = [
  {
    id: 'scm-1',
    name: 'NGEP GitHub Enterprise',
    provider: 'GitHub Enterprise Server',
    baseUrl: 'https://git.corp.example',
    apiUrl: 'https://git.corp.example/api/v3',
    repository: 'platform/ngep',
    proxyPolicy: '直连私网，禁止环境代理',
    caFingerprint: 'SHA256:5A:9C:…:7E:21',
    credentialLabel: 'GitHub App · key-2026-q3',
    status: 'healthy',
    checkedAt: '2026-08-20 13:50',
  },
  {
    id: 'scm-2',
    name: 'Xminds GitLab',
    provider: 'GitLab Self-Managed',
    baseUrl: 'https://gitlab.dev.example',
    apiUrl: 'https://gitlab.dev.example/api/v4',
    repository: 'platform/xminds-agent',
    proxyPolicy: '企业代理，固定 DNS',
    caFingerprint: 'SHA256:38:1B:…:A2:09',
    credentialLabel: 'Project Access Token · 2026-10 到期',
    status: 'attention',
    checkedAt: '2026-08-20 11:24',
  },
];

export const endpoints: DistributionEndpoint[] = [
  {
    id: 'endpoint-1',
    name: '华东主 Origin',
    kind: 'Origin',
    region: 'cn-east-1',
    priority: 10,
    health: 'healthy',
    rootDigest: 'sha256:8d10…e291',
    timestampDigest: 'sha256:49a0…1c4e',
    checkedAt: '2026-08-20 13:52:08',
  },
  {
    id: 'endpoint-2',
    name: '全国 CDN',
    kind: 'CDN',
    region: 'cn-global',
    priority: 20,
    health: 'healthy',
    rootDigest: 'sha256:8d10…e291',
    timestampDigest: 'sha256:49a0…1c4e',
    checkedAt: '2026-08-20 13:51:44',
  },
  {
    id: 'endpoint-3',
    name: '研发隔离区',
    kind: 'Private',
    region: 'lab-offline',
    priority: 30,
    health: 'degraded',
    rootDigest: 'sha256:8d10…e291',
    timestampDigest: 'sha256:98c1…5720',
    checkedAt: '2026-08-20 13:49:20',
  },
];

export const auditEvents: AuditEvent[] = [
  {
    id: 'evt-1',
    time: '2026-08-20 13:46:22',
    product: 'ngep',
    actor: 'Alice 发布者',
    action: 'release.submit',
    target: 'Release 1.2.3',
    result: 'success',
    requestId: 'req_01J5A0JH8Q4V',
    releaseId: 'release-1',
    summary: '提交 Release，等待不同审批者审批。',
  },
  {
    id: 'evt-2',
    time: '2026-08-20 11:26:05',
    product: 'xminds-agent',
    actor: 'Release Worker',
    action: 'endpoint.sync',
    target: '研发隔离区',
    result: 'failed',
    requestId: 'req_01J5A0KQ12XM',
    releaseId: 'release-3',
    summary: '目标端 timestamp 摘要回读不一致，已进入受控重试。',
  },
  {
    id: 'evt-3',
    time: '2026-08-19 18:20:19',
    product: 'ngep',
    actor: 'Bob 审批者',
    action: 'release.publish',
    target: 'Release 1.2.2',
    result: 'success',
    requestId: 'req_01J59YAXHF91',
    releaseId: 'release-2',
    summary: '可信目录已签名并分发至两个健康端点。',
  },
];

export const logCenterEvents: LogCenterEvent[] = [
  ...auditEvents.map((event) => ({ ...event, kind: 'operation' as const })),
  {
    id: 'auth-1',
    kind: 'authentication',
    time: '2026-08-20 13:40:08',
    product: 'ngep',
    actor: 'Alice 发布者',
    action: 'auth.sso.login',
    target: '企业身份平台',
    result: 'success',
    decision: 'allow',
    requestId: 'req_01J5A0J1S9D2',
    summary: 'OIDC 单点登录成功，角色与产品范围已同步。',
  },
  {
    id: 'app-1',
    kind: 'application',
    time: '2026-08-20 13:38:12',
    product: 'ngep',
    actor: 'ngep-desktop',
    action: 'license.check',
    target: '/api/v1/releases/latest',
    result: 'success',
    decision: 'allow',
    requestId: 'req_01J59ZQ0V2K8',
    clientAppId: 'com.xminds.ngep.desktop',
    clientAppVersion: '2.4.0',
    authorizationName: 'Next-Gen Enterprise Portal 商业授权',
    licenseId: 'LIC-2026-000184',
    licenseExpiresAt: '2026-12-31 23:59:59',
    summary: '客户端请求最新 Release，授权快照可信且未过期。',
  },
  {
    id: 'git-1',
    kind: 'git',
    time: '2026-08-20 13:36:41',
    product: 'xminds-agent',
    actor: 'Release Worker',
    action: 'git.sync',
    target: 'platform/xminds-agent',
    result: 'success',
    requestId: 'req_01J59ZK6A4E1',
    provider: 'GitLab Self-Managed',
    repository: 'platform/xminds-agent',
    syncStage: 'fetch + manifest verify',
    summary: '同步 main 分支并完成提交摘要校验。',
  },
];
